In [21]:
import time
import numpy as np
user = 1684

t1 = time.time()
# matrix = [[0 for _ in range(user)] for _ in range(user)]
matrix_numpy = np.zeros((user,user)).tolist()
diagonal = np.diag_indices(user)

t2 = time.time()
print(f"time cost = {t2-t1}")

time cost = 0.1315915584564209

In [4]:
a = (1)

print(type(a))

<class 'int'>

In [12]:
df_matrix_numpy

,0,1,2,3,4,5,6,7,8,9,...,1674,1675,1676,1677,1678,1679,1680,1681,1682,1683
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1679,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1681,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1682,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1683,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
import time
import random


result = []
t1 = time.time()
for i in range(user) :
    result_inner = []
    for j in range(i,user) :
        if i == j :
            result.append(1)
        random_int = random.randint(0,1)
        result_inner.append(random_int)
    result.append(result_inner)
t2 = time.time()
print(f"Time Cost = {t2-t1}")

Time Cost = 1.6329727172851562

In [16]:
import pandas as pd 


pd.DataFrame(result)

         0
0        1
1        0
2        0
3        1
4        0
...     ..
1420449  1
1420450  1
1420451  0
1420452  1
1420453  0

[1420454 rows x 1 columns]