In [2]:
# from openpyxl import Workbook

# import the python pandas package
import pandas as pd
 
# create  data_frame1 by creating a dictionary
# in which values are stored as list
data_frame1 = pd.DataFrame({'Fruits': ['Appple', 'Banana', 'Mango',
                                       'Dragon Fruit', 'Musk melon', 'grapes'],
                            'Sales in kg': [21, 30, 15, 10, 50, 40]})
 
# create  data_frame2 by creating a dictionary 
# in which values are stored as list
data_frame2 = pd.DataFrame({'Vegetables': ['tomato', 'Onion', 'ladies finger',
                                           'beans', 'bedroot', 'carrot'],
                            'Sales in kg': [200, 310, 115, 110, 55, 45]})
 
# create  data_frame3 by creating a dictionary 
# in which values are stored as list
data_frame3 = pd.DataFrame({'Baked Items': ['Cakes', 'biscuits', 'muffins',
                                            'Rusk', 'puffs', 'cupcakes'],
                            'Sales in kg': [120, 130, 159, 310, 150, 140]})
 
print(data_frame1)
print(data_frame2)
print(data_frame3)
 
# create a excel writer object
with pd.ExcelWriter("filename.xlsx") as writer:
   
    # use to_excel function and specify the sheet_name and index 
    # to store the dataframe in specified sheet
    data_frame1.to_excel(writer, sheet_name="Fruits", index=False)
    data_frame2.to_excel(writer, sheet_name="Vegetables", index=False)
    data_frame3.to_excel(writer, sheet_name="Baked Items", index=False)

         Fruits  Sales in kg
0        Appple           21
1        Banana           30
2         Mango           15
3  Dragon Fruit           10
4    Musk melon           50
5        grapes           40
      Vegetables  Sales in kg
0         tomato          200
1          Onion          310
2  ladies finger          115
3          beans          110
4        bedroot           55
5         carrot           45
  Baked Items  Sales in kg
0       Cakes          120
1    biscuits          130
2     muffins          159
3        Rusk          310
4       puffs          150
5    cupcakes          140

In [3]:
import pandas as pd
    
old_data = pd.read_excel("filename.xlsx",sheet_name="Vegetables")

In [4]:
old_data

      Vegetables  Sales in kg
0         tomato          200
1          Onion          310
2  ladies finger          115
3          beans          110
4        bedroot           55
5         carrot           45

In [5]:
basket = {"ring" : []}
balls = ["Volley","Sattle Cock","Foot Ball","Basket Ball"]

for i in balls :
    basket["ring"] += [i]

In [6]:
import pandas as pd

metadata = {
    "alpa_1": [],
    "alpa_2": [],
    "k": [],
}

alpha_1 = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
alpha_2 = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]

k = [5,10,15,18,20,25,30,40,50,100,200]

for a in alpha_1 :
    for b in alpha_2 :
        for c in k :
            metadata["alpa_1"] += [a]
            metadata["alpa_2"] += [b]
            metadata["k"] += [c]


metadata = pd.DataFrame(metadata)

with pd.ExcelWriter("evaluation.xlsx") as writer :
    metadata.to_excel(writer,sheet_name="user-based")

In [7]:
from MatrixRating import MatrixRating

df = MatrixRating("data/ml-100k")

In [8]:
df.show_dataset()

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
import pandas as pd
import numpy as np
import openpyxl

print(pd.__version__)
print(np.__version__)
print(openpyxl.__version__)

p = None
print(p is not None)

2.2.3
2.2.2
3.1.5
False

In [1]:
import Evaluation as E 
import DistanceBased.similarities as S 

ti = S.TI("data/ml-100k",opsional="item-based",alpha_1=0.1,alpha_2=0.5,k=5)

evaluation = E.NDCG("data/ml-100k",ti.get_top_n(),toyData=False)

True
Train index = 0
Train index = 1
Train index = 2
Train index = 3
Train index = 4
Train index = 0
Train index = 1
Train index = 2
Train index = 3
Train index = 4
DCG =  1.4314481474717027 IDCG =  9.161581041840885
DCG =  0.227670248696953 IDCG =  9.161581041840885
DCG =  0.6309297535714575 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.23137821315975915 IDCG =  9.161581041840885
DCG =  1.666334209877697 IDCG =  9.161581041840885
DCG =  0.927321778153335 IDCG =  9.161581041840885
DCG =  0.6582897750776974 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.9013308787554337 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.9435721267976197 IDCG =  9.161581041840885
DCG =  2.4105314488428253 IDCG =  9.161581041840885
DCG =  0.3010299956639812 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  2.3333695402240884 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.1162414726454695 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.25 IDCG =  9.161581041840885
DCG =  0.47066413271370305 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.227670248696953 IDCG =  9.161581041840885
DCG =  1.0299576396437142 IDCG =  9.161581041840885
DCG =  0.7338402147650842 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.6166617346267655 IDCG =  9.161581041840885
DCG =  0.25 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.31546487678572877 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.23981246656813146 IDCG =  9.161581041840885
DCG =  0.21274605355336318 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.22424382421757544 IDCG =  9.161581041840885
DCG =  2.583104088552618 IDCG =  9.161581041840885
DCG =  2.694512941401582 IDCG =  9.161581041840885
DCG =  0.958706832903933 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3010299956639812 IDCG =  9.161581041840885
DCG =  1.4368399089808015 IDCG =  9.161581041840885
DCG =  0.27894294565112987 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.38685280723454163 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.333350055227357 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.8153618690753262 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  2.0152265034981127 IDCG =  9.161581041840885
DCG =  1.6496903321788703 IDCG =  9.161581041840885
DCG =  0.6598636842586093 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.2360949329673043 IDCG =  9.161581041840885
DCG =  0.4412557458270727 IDCG =  9.161581041840885
DCG =  1.1332281428089943 IDCG =  9.161581041840885
DCG =  1.2649609873821372 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.4284142098426841 IDCG =  9.161581041840885
DCG =  0.4740332015178259 IDCG =  9.161581041840885
DCG =  0.26264953503719357 IDCG =  9.161581041840885
DCG =  0.21533827903669653 IDCG =  9.161581041840885
DCG =  1.1361344480886366 IDCG =  9.161581041840885
DCG =  0.3010299956639812 IDCG =  9.161581041840885
DCG =  0.25 IDCG =  9.161581041840885
DCG =  0.2890648263178879 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.27023815442731974 IDCG =  9.161581041840885
DCG =  0.5772719165655259 IDCG =  9.161581041840885
DCG =  1.5582720951629239 IDCG =  9.161581041840885
DCG =  1.2138456680859573 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  2.318173077313367 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.1105226206466625 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  2.769193467362082 IDCG =  9.161581041840885
DCG =  1.418387094534183 IDCG =  9.161581041840885
DCG =  1.0370323373082715 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.6462885238311038 IDCG =  9.161581041840885
DCG =  0.6646039206858575 IDCG =  9.161581041840885
DCG =  1.5465805178552703 IDCG =  9.161581041840885
DCG =  2.002108489783435 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.9241698773972788 IDCG =  9.161581041840885
DCG =  0.26264953503719357 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.20584683246043448 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  2.721725898932898 IDCG =  9.161581041840885
DCG =  0.2037950470905062 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.23540891336663824 IDCG =  9.161581041840885
DCG =  0.47424382421757544 IDCG =  9.161581041840885
DCG =  0.8076431900120641 IDCG =  9.161581041840885
DCG =  0.47608498688775425 IDCG =  9.161581041840885
DCG =  0.5261961792371352 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.31546487678572877 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.5143518590177681 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.31546487678572877 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  2.369395851444523 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.7414288341552103 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.5569880204737967 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.6569998321869278 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.4770227542673192 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.20801459767650948 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.3352254080614199 IDCG =  9.161581041840885
DCG =  0.932125405563094 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.7774576000464557 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.23540891336663824 IDCG =  9.161581041840885
DCG =  0.42485977654800994 IDCG =  9.161581041840885
DCG =  0.21274605355336318 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.21810429198553155 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.22106472945750374 IDCG =  9.161581041840885
DCG =  0.21533827903669653 IDCG =  9.161581041840885
DCG =  0.21810429198553155 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.2037950470905062 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.6657957528856715 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.2559580248098155 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3010299956639812 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.26264953503719357 IDCG =  9.161581041840885
DCG =  2.2567310498491793 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3333333333333333 IDCG =  9.161581041840885
DCG =  0.5163682747006777 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.6343633289973145 IDCG =  9.161581041840885
DCG =  0.21533827903669653 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.2559580248098155 IDCG =  9.161581041840885
DCG =  1.8861216190845476 IDCG =  9.161581041840885
DCG =  0.21810429198553155 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.8346798714791825 IDCG =  9.161581041840885
DCG =  0.45351320535216977 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.7337893923193908 IDCG =  9.161581041840885
DCG =  1.3416793848309874 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.859594012259695 IDCG =  9.161581041840885
DCG =  1.6403130546075975 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.27894294565112987 IDCG =  9.161581041840885
DCG =  0.8207058087273156 IDCG =  9.161581041840885
DCG =  1.6652970340491788 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3333333333333333 IDCG =  9.161581041840885
DCG =  1.2141561772549059 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.227670248696953 IDCG =  9.161581041840885
DCG =  0.5510299956639813 IDCG =  9.161581041840885
DCG =  0.8008160485984177 IDCG =  9.161581041840885
DCG =  0.5408424622321126 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.9559040964578762 IDCG =  9.161581041840885
DCG =  4.031793146301045 IDCG =  9.161581041840885
DCG =  0.5391801657937678 IDCG =  9.161581041840885
DCG =  0.9640304555642843 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.89527201342591 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.4940277481969527 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.44412426671312233 IDCG =  9.161581041840885
DCG =  0.4688943663358015 IDCG =  9.161581041840885
DCG =  3.1219938369900833 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.5552773433538603 IDCG =  9.161581041840885
DCG =  0.23540891336663824 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.442348116203107 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.4524429426172629 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.2559580248098155 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.5077851304100856 IDCG =  9.161581041840885
DCG =  0.26264953503719357 IDCG =  9.161581041840885
DCG =  0.23137821315975915 IDCG =  9.161581041840885
DCG =  0.8276145580211597 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.8187422466999715 IDCG =  9.161581041840885
DCG =  1.6944184605945232 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.44412426671312233 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.45012238442528396 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.26264953503719357 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.4860870513820699 IDCG =  9.161581041840885
DCG =  0.9096495546595743 IDCG =  9.161581041840885
DCG =  0.9361996900691436 IDCG =  9.161581041840885
DCG =  0.2037950470905062 IDCG =  9.161581041840885
DCG =  2.160130293456015 IDCG =  9.161581041840885
DCG =  0.5654648767857288 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.20184908658209985 IDCG =  9.161581041840885
DCG =  2.448943552489156 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.7210647294575038 IDCG =  9.161581041840885
DCG =  0.20584683246043448 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.22106472945750374 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.20584683246043448 IDCG =  9.161581041840885
DCG =  1.079733918170851 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.7789429456511299 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.9167835606812945 IDCG =  9.161581041840885
DCG =  1.608835839773531 IDCG =  9.161581041840885
DCG =  0.2559580248098155 IDCG =  9.161581041840885
DCG =  0.43517326025026537 IDCG =  9.161581041840885
DCG =  0.7216979968939057 IDCG =  9.161581041840885
DCG =  0.9772745215527444 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.9636427611275615 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.7320733540515374 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.7831550073210012 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.9973868589650259 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  3.8424318524511305 IDCG =  9.161581041840885
DCG =  0.9662659319322966 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.8658095206754592 IDCG =  9.161581041840885
DCG =  1.6867512000425646 IDCG =  9.161581041840885
DCG =  3.2809026431035435 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.8405024516367527 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.6593600378126042 IDCG =  9.161581041840885
DCG =  1.6378766245475074 IDCG =  9.161581041840885
DCG =  1.5613198661570742 IDCG =  9.161581041840885
DCG =  0.4854089133666383 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.5337153684361139 IDCG =  9.161581041840885
DCG =  2.3356168016344947 IDCG =  9.161581041840885
DCG =  0.6376058301013732 IDCG =  9.161581041840885
DCG =  1.7571109213779814 IDCG =  9.161581041840885
DCG =  0.42076065122987266 IDCG =  9.161581041840885
DCG =  0.4556220373773346 IDCG =  9.161581041840885
DCG =  0.25 IDCG =  9.161581041840885
DCG =  0.4667871265263974 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.20184908658209985 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.2890648263178879 IDCG =  9.161581041840885
DCG =  0.20801459767650948 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.6628435089472183 IDCG =  9.161581041840885
DCG =  0.7898069761574753 IDCG =  9.161581041840885
DCG =  0.9596570287847537 IDCG =  9.161581041840885
DCG =  0.4314652957874592 IDCG =  9.161581041840885
DCG =  1.460549383951682 IDCG =  9.161581041840885
DCG =  1.3809727299641787 IDCG =  9.161581041840885
DCG =  0.3562071871080222 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3333333333333333 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.9317828611643963 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.6875093115852036 IDCG =  9.161581041840885
DCG =  0.6954840462949993 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.4436075136586375 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.23540891336663824 IDCG =  9.161581041840885
DCG =  0.3562071871080222 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.48054807228447227 IDCG =  9.161581041840885
DCG =  1.7144333969141587 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.518607559847009 IDCG =  9.161581041840885
DCG =  0.46748271526508445 IDCG =  9.161581041840885
DCG =  0.9902153202156557 IDCG =  9.161581041840885
DCG =  0.2890648263178879 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.8663386669380958 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.1332612188054196 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.5642673865281378 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.22106472945750374 IDCG =  9.161581041840885
DCG =  0.49577049137794693 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.7692627293852764 IDCG =  9.161581041840885
DCG =  2.315056662563694 IDCG =  9.161581041840885
DCG =  0.2037950470905062 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  2.490658170134754 IDCG =  9.161581041840885
DCG =  2.1197907352133747 IDCG =  9.161581041840885
DCG =  0.43344257102222805 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.7004973745786605 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.0568318149621825 IDCG =  9.161581041840885
DCG =  0.4688943663358015 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.9306765580733931 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.2875215876932773 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885

In [17]:
import pandas as pd

pd.set_option('display.max_colwidth', None)

In [2]:
print(evaluation.get_top_n_specific_user(4,indexTrain=0)[:10])
print(evaluation.get_top_n_specific_user(4,indexTrain=0))
print(ti.get_prediction_array()[0][4][1020])

[1466, 1374, 1536, 1020, 1499, 512, 319, 1652, 113, 1239]
[1466, 1374, 1536, 1020, 1499, 512, 319, 1652, 113, 1239, 1638, 887, 523, 602, 1496, 22, 744, 1448, 427, 652, 458, 473, 612, 1630, 312, 482, 112, 63, 1200, 1190, 1158, 514, 1366, 198, 640, 810, 1019, 1287, 662, 186, 804, 1628, 849, 1141, 488, 208, 653, 1622, 616, 492, 855, 1061, 177, 1673, 480, 32, 204, 510, 1018, 479, 1188, 21, 520, 1121, 866, 1591, 78, 912, 1635, 1644, 1649, 1650, 1557, 1641, 434, 1387, 1450, 614, 944, 1202, 245, 483, 953, 155, 1120, 371, 126, 1376, 1157, 1515, 292, 1192, 264, 901, 1346, 1599, 88, 257, 522, 489, 11, 1642, 95, 762, 1066, 918, 99, 478, 1615, 509, 27, 314, 1194, 194, 850, 81, 1505, 1447, 1297, 29, 1265, 1166, 895, 526, 247, 1489, 529, 1148, 1498, 0, 1367, 315, 127, 299, 1343, 836, 172, 1523, 1611, 332, 297, 905, 317, 97, 250, 645, 694, 656, 834, 647, 1461, 67, 133, 275, 183, 197, 294, 610, 270, 153, 1143, 122, 1201, 116, 301, 1124, 964, 30, 74, 1117, 118, 474, 1096, 1598, 606, 646, 1267, 8, 1242, 1455, 862, 55, 1525, 149, 643, 46, 1118, 470, 633, 655, 1130, 536, 1128, 1085, 241, 1467, 1360, 393, 914, 331, 748, 271, 700, 852, 1593, 1471, 18, 528, 296, 205, 908, 871, 605, 174, 1185, 867, 1204, 1191, 14, 252, 792, 1663, 1481, 248, 255, 903, 1484, 1369, 1197, 1509, 1232, 1098, 926, 267, 107, 1397, 1074, 269, 704, 1052, 287, 68, 175, 281, 513, 878, 1534, 428, 202, 307, 338, 732, 771, 23, 567, 717, 1110, 1236, 750, 236, 915, 951, 190, 650, 240, 1401, 505, 192, 1092, 1404, 1590, 295, 504, 1588, 835, 1015, 1546, 223, 588, 1655, 477, 507, 844, 600, 189, 92, 1524, 525, 210, 1006, 1196, 644, 384, 143, 518, 272, 1216, 1511, 356, 221, 191, 73, 1480, 178, 1205, 493, 123, 327, 1603, 603, 6, 1017, 1186, 1154, 1606, 147, 54, 459, 519, 170, 117, 345, 788, 683, 1465, 711, 481, 160, 284, 899, 1341, 1250, 545, 1247, 1064, 212, 543, 557, 888, 325, 1165, 690, 617, 1237, 542, 934, 1426, 1038, 1264, 7, 565, 300, 592, 969, 1159, 145, 1627, 498, 1072, 3, 31, 497, 10, 59, 1129, 741, 409, 535, 709, 1079, 181, 61, 410, 1114, 164, 607, 747, 579, 1510, 26, 1069, 882, 660, 289, 1225, 485, 353, 402, 1203, 1528, 1552, 1559, 333, 490, 760, 1645, 658, 1199, 751, 1474, 1151, 577, 1261, 1152, 347, 1399, 463, 1385, 886, 1, 108, 165, 1490, 114, 1428, 1035, 1473, 254, 9, 1378, 298, 444, 358, 231, 1167, 596, 531, 657, 517, 128, 546, 495, 40, 146, 184, 1122, 854, 487, 432, 1403, 1021, 637, 476, 561, 176, 883, 91, 898, 967, 1487, 784, 1016, 957, 169, 1133, 1451, 727, 501, 1065, 1393, 933, 791, 1083, 166, 853, 1384, 187, 692, 524, 1002, 1077, 1171, 674, 611, 670, 251, 1506, 1272, 1097, 864, 229, 196, 82, 1482, 1251, 989, 360, 47, 521, 976, 1361, 1425, 1601, 268, 789, 1026, 811, 1438, 714, 1219, 125, 12, 1222, 1610, 1217, 720, 1577, 1629, 1631, 1632, 1634, 1636, 1637, 1639, 1640, 1646, 1648, 1105, 1537, 843, 549, 1137, 425, 527, 261, 124, 1405, 293, 39, 965, 1304, 749, 1183, 1255, 587, 1279, 330, 233, 469, 689, 148, 16, 1584, 1168, 737, 322, 310, 1277, 131, 649, 677, 712, 805, 239, 1112, 1260, 1604, 2, 917, 303, 115, 1008, 1153, 1483, 421, 642, 1386, 1572, 552, 460, 865, 491, 1389, 1476, 1666, 1667, 1669, 1170, 86, 152, 37, 581, 1146, 623, 306, 1500, 1115, 1013, 38, 1444, 1503, 335, 1215, 1420, 340, 812, 846, 984, 907, 1513, 1427, 1408, 486, 1518, 593, 1398, 179, 684, 678, 580, 530, 506, 904, 285, 462, 422, 1068, 1106, 213, 70, 695, 641, 1042, 1259, 881, 496, 511, 1323, 615, 575, 283, 13, 90, 719, 793, 534, 4, 1011, 1614, 1514, 1210, 211, 724, 1295, 970, 756, 200, 1049, 923, 548, 1486, 243, 608, 651, 962, 1211, 916, 1193, 1144, 1681, 1010, 556, 1123, 798, 45, 1207, 945, 745, 1000, 85, 894, 1240, 1135, 1071, 1198, 1147, 1173, 802, 106, 156, 1283, 801, 823, 363, 515, 362, 733, 942, 1136, 136, 342, 235, 339, 158, 96, 320, 220, 53, 631, 763, 1592, 1326, 290, 1004, 1014, 946, 848, 278, 105, 230, 729, 1479, 936, 902, 847, 685, 396, 302, 89, 728, 837, 609, 1395, 1089, 1175, 601, 773, 1619, 863, 328, 590, 34, 305, 1070, 591, 913, 1223, 688, 58, 988, 465, 420, 1300, 348, 800, 1142, 1602, 1495, 1055, 135, 665, 1149, 1325, 755, 392, 638, 532, 803, 1031, 1094, 832, 1334, 1244, 868, 809, 1125, 746, 1067, 64, 1400, 540, 799, 237, 620, 968, 1394, 752, 309, 924, 824, 697, 1027, 781, 664, 731, 206, 775, 1140, 1321, 1268, 1417, 654, 627, 713, 1084, 663, 288, 1073, 952, 151, 17, 1086, 779, 326, 573, 959, 1030, 357, 1033, 874, 1195, 1380, 280, 308, 1063, 1044, 730, 381, 1320, 1314, 329, 790, 1478, 355, 806, 858, 648, 977, 157, 599, 406, 1169, 553, 974, 675, 43, 350, 1102, 765, 244, 1543, 435, 159, 101, 222, 1659, 758, 48, 1005, 361, 1554, 635, 613, 723, 1521, 780, 274, 890, 1104, 838, 921, 41, 1145, 15, 1312, 972, 1107, 60, 676, 820, 1180, 1037, 1046, 19, 1045, 869, 911, 1270, 66, 57, 472, 1381, 1057, 925, 1390, 226, 796, 500, 516, 625, 787, 860, 956, 1345, 1383, 1550, 1587, 1589, 1243, 36, 1040, 721, 1661, 667, 344, 1379, 699, 996, 277, 734, 80, 948, 604, 1003, 928, 141, 978, 782, 681, 630, 876, 634, 1331, 738, 774, 595, 494, 93, 1551, 195, 1422, 503, 772, 991, 142, 279, 537, 1414, 632, 1213, 1109, 286, 130, 963, 1178, 708, 354, 629, 582, 324, 1530, 502, 359, 797, 966, 707, 761, 919, 1443, 739, 569, 1081, 1377, 696, 1439, 1127, 821, 636, 693, 343, 1029, 282, 740, 1520, 457, 669, 1454, 1296, 1274, 1656, 388, 273, 475, 390, 1233, 1076, 586, 1549, 999, 808, 825, 1430, 618, 1421, 318, 461, 566, 572, 1189, 570, 1555, 873, 1424, 77, 897, 1271, 417, 291, 1357, 110, 471, 910, 1468, 754, 1100, 971, 376, 216, 1131, 416, 323, 550, 827, 859, 304, 259, 992, 217, 1355, 265, 346, 551, 1531, 940, 1228, 1618, 1529, 935, 624, 76, 814, 499, 786, 778, 1293, 1276, 564, 1299, 576, 842, 154, 1516, 1544, 1281, 568, 1134, 958, 1051, 554, 1440, 817, 1001, 1054, 1184, 1022, 71, 1254, 25, 1036, 1330, 941, 1090, 1311, 1248, 1310, 1352, 349, 880, 316, 815, 84, 163, 1657, 533, 1080, 140, 1502, 1472, 1469, 1607, 826, 1048, 56, 1179, 997, 263, 1540, 1446, 1449, 1459, 1522, 715, 258, 1023, 687, 1494, 892, 870, 736, 1441, 819, 72, 594, 1317, 1434, 979, 877, 219, 1024, 981, 706, 52, 466, 885, 900, 1285, 764, 42, 1082, 399, 1453, 679, 1238, 1322, 659, 770, 334, 973, 1241, 922, 585, 673, 1337, 1435, 1553, 1633, 1647, 1412, 703, 909, 1470, 1058, 1501, 1680, 735, 1269, 1132, 1508, 1609, 555, 931, 1517, 336, 1218, 1091, 1032, 1442, 401, 906, 1429, 1332, 1336, 1087, 138, 1548, 937, 558, 1676, 276, 845, 383, 1263, 1056, 1329, 5, 337, 705, 1273, 341, 1605, 1315, 321, 1477, 1053, 1289, 807, 993, 443, 1007, 1416, 1662, 1664, 1665, 1668, 75, 626, 1113, 1212, 51, 468, 875, 794, 990, 1050, 102, 260, 1371, 628, 1230, 214, 1354, 961, 759, 1172, 1229, 35, 201, 1214, 1059, 767, 1302, 484, 44, 453, 1674, 818, 1266, 311, 1406, 840, 932, 1252, 266, 716, 1257, 702, 1138, 766, 954, 562, 1507, 1458, 743, 1423, 891, 1012, 1041, 1028, 1301, 1150, 1221, 672, 994, 464, 452, 1187, 578, 986, 378, 726, 456, 1177, 1278, 1418, 1156, 1139, 1327, 218, 369, 1463, 1411, 698, 1209, 508, 938, 1111, 1108, 368, 722, 929, 1009, 1231, 1034, 1282, 1262, 841, 571, 621, 1047, 1350, 440, 79, 943, 467, 777, 686, 1060, 955, 1539, 1541, 831, 352, 1160, 1298, 50, 691, 547, 879, 1224, 1088, 1596, 985, 1388, 1245, 1445, 830, 1464, 1043, 583, 1402, 1335, 960, 119, 769, 998, 560, 539, 872, 666, 816, 589, 983, 253, 1436, 639, 1116, 753, 718, 1368, 768, 132, 1176, 1597, 828, 930, 1093, 121, 1280, 987, 559, 949, 1409, 1182, 927, 1099, 950, 1163, 1370, 975, 1643, 1396, 1256, 889, 1075, 839, 795, 861, 1658, 1275, 1126, 242, 742, 725, 1626, 1227, 563, 1433, 947, 1078, 1181, 1307, 1358, 137, 783, 1103, 1305, 1306, 1333, 1545, 1547, 1558, 1563, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1573, 1574, 1575, 1576, 1578, 1579, 1580, 1582, 1583, 1586, 822, 387, 671, 661, 544, 584, 1407, 682, 597, 538, 668, 1526, 1437, 619, 920, 1291, 1613, 1039, 884, 776, 224, 1208, 1318, 1538, 995, 1249, 412, 1162, 262, 1415, 1220, 1344, 982, 1413, 622, 1062, 375, 541, 574, 1294, 1654, 1527, 1101, 1485, 1493, 33, 896, 1660, 83, 1206, 129, 1253, 680, 351, 1164, 1621, 1353, 1025, 1452, 1460, 1290, 1651, 1373, 1419, 1226, 1410, 1382, 1119, 1600, 1512, 857, 1608, 1286, 423, 111, 1316, 1095, 1671, 980, 109, 833, 939, 1284, 701, 1488, 785, 1653, 893, 1675, 438, 1594, 1595, 1303, 757, 1672, 87, 103, 139, 1359, 1161, 1313, 1392, 1288, 246, 1391, 1246, 1533, 1258, 1617, 1475, 1364, 1324, 1328, 1338, 1339, 1340, 1348, 1349, 1351, 1362, 1365, 313, 1375, 1625, 598, 710, 813, 829, 851, 856, 1155, 1174, 1234, 1235, 1292, 1308, 1309, 1319, 1342, 1347, 1356, 1363, 1372, 1431, 1432, 1456, 1457, 1462, 1491, 1492, 1497, 1504, 1519, 1532, 1535, 1542, 1556, 1560, 1561, 1562, 1564, 1581, 1585, 1612, 1616, 1623, 1624, 1670, 1677, 1678, 1679, 1620]
5.21471607869225

In [6]:
from operator import itemgetter

prediction_user_4_fold_1 = ti.get_prediction_array()[0][4]

# top_n_value = [prediction_user_4_fold_1[i] for i in evaluation.getItem(4,interacted=False,indexTrain=0)[:10]]
# print(top_n_value)
print(itemgetter(*evaluation.top_n[0][4])(prediction_user_4_fold_1))

sort_new =  sorted(evaluation.getItem(4,interacted=False,indexTrain=0),key=lambda x : prediction_user_4_fold_1[x], reverse=True)

(5.719023742583455, 5.411684566864092, 5.273543266278282, 5.21471607869225, 5.132335552348402, 5.103802202042152, 4.977452813936131, 4.944970072759129, 4.883004717056317, 4.866108797035027, 4.861462301991333, 4.85559627389256, 4.838079720149866, 4.835140077579352, 4.815193033286986, 4.790826816560027, 4.772003337835814, 4.745408123360261, 4.725801702422762, 4.70282951036911, 4.696842996267967, 4.696342857271082, 4.6787480845711436, 4.659379781625404, 4.658434937778645, 4.6223067023055195, 4.603920120975594, 4.599689311942579, 4.59890783253499, 4.597882400586642, 4.591633441563337, 4.583237677023467, 4.574226928941219, 4.572459425711541, 4.566943830371889, 4.5444511632677935, 4.5295682589587285, 4.520784778730045, 4.5187123561479465, 4.518069953296329, 4.501029114117525, 4.499917301079998, 4.493931447884263, 4.49340029786065, 4.490346722836932, 4.488984294707959, 4.488765481925839, 4.487582468585395, 4.467946678279443, 4.457140821443113, 4.4570158764533545, 4.449693628544859, 4.431817377065781, 4.428848272506799, 4.427233665465401, 4.421530399370945, 4.421312589424365, 4.419815365782555, 4.4164977906776475, 4.416292963685212, 4.410989060528821, 4.398636018444293, 4.38076220127193, 4.367460847555337, 4.366396565423121, 4.361568512925348, 4.353611607619695, 4.339083078792268, 4.339083078792268, 4.339083078792268, 4.339083078792268, 4.339083078792268, 4.33757623247855, 4.334944980239607, 4.331163953699349, 4.328274738572635, 4.324449247036821, 4.32193788672475, 4.321738464714917, 4.320225764130328, 4.315473081648159, 4.310090945465983, 4.307434216004881, 4.294832028445219, 4.2947240266473665, 4.290008931004416, 4.281256259196493, 4.275649995301228, 4.273712874549959, 4.273508805561918, 4.273068934980786, 4.2666317704517835, 4.266074158868611, 4.264579448877906, 4.257243931868371, 4.235605236717855, 4.2351055756040985, 4.22742253048905, 4.22168342911256, 4.217961379885038, 4.21481363712266, 4.211792644523609, 4.211210451700008, 4.20812865291658, 4.193961614104181, 4.18747930825859, 4.182340115057445, 4.177869719812231, 4.176415666542552, 4.168096382488743, 4.1677775571126245, 4.163414930905885, 4.16086942343503, 4.160399488963508, 4.157178197189912, 4.155953259881575, 4.155740124903999, 4.150776926418557, 4.14561972514411, 4.143534281697264, 4.132638561138626, 4.132576878770743, 4.131793771451236, 4.1107748422660535, 4.107991500071364, 4.101572546411382, 4.101128519860383, 4.1000407452412375, 4.099661823643011, 4.0985275918671835, 4.098140812187357, 4.094768201345678, 4.08725109598721, 4.084545916512057, 4.0816747494220476, 4.071820154969777, 4.070421284354029, 4.0673013745611515, 4.066836693917783, 4.066544713334677, 4.064149648171151, 4.055580728051427, 4.048464442070771, 4.0479462936294155, 4.045204955135248, 4.037342130232604, 4.036830249788061, 4.03319364226134, 4.032686068509291, 4.0270829216386685, 4.026270120695139, 4.024921011763943, 4.023141055386433, 4.022747584866865, 4.021480238321548, 4.013691445843194, 4.013375082156746, 4.012994575715253, 4.007000771865345, 4.005746768570241, 4.00078087454736, 4.000405879902646, 4.000275283356235, 3.9995263868029975, 3.9966471351550603, 3.9958011267836056, 3.9932001387898097, 3.984277545814703, 3.980925036291824, 3.975069889364047, 3.974686294488171, 3.9726385943919182, 3.9725691335946727, 3.972334013309839, 3.971557348153288, 3.970352935592609, 3.967665663450262, 3.9643123479353517, 3.9627266512091137, 3.9615908573792655, 3.9593424126097165, 3.9513969505164215, 3.951212694262985, 3.950322592989491, 3.950172175045265, 3.947286548492931, 3.9385732781503178, 3.938191264272813, 3.936541929198351, 3.933788869374825, 3.931445634211394, 3.930261019020359, 3.9300088474894963, 3.928536531223316, 3.928151390813076, 3.923600941840118, 3.923524220083355, 3.9216338495218235, 3.9206603622586513, 3.918862836199931, 3.9176136815843443, 3.915368098855859, 3.914957240658885, 3.9112466286898164, 3.910989060528821, 3.9000599171130506, 3.899294510513481, 3.897880681745347, 3.8976531163175347, 3.895138173166312, 3.8879892234237525, 3.8869732626892444, 3.8836136428382706, 3.8765420645707365, 3.8762669464068864, 3.868050347455206, 3.8674308484683944, 3.864905400076575, 3.8636363241024383, 3.8628046487967755, 3.857344807625074, 3.857129200855867, 3.8470788472183037, 3.844324755918976, 3.8428283748176653, 3.8410296951222085, 3.840114637103076, 3.836583451882257, 3.8342010572387983, 3.828128262920264, 3.826882881473203, 3.8248445182679345, 3.822915709205076, 3.822738581766575, 3.8224697634046025, 3.818853366706487, 3.818287908531554, 3.8175750985106367, 3.8120546484117144, 3.810552516596056, 3.8103311104068665, 3.8098668725570968, 3.809058209335348, 3.803956873752439, 3.801802035122493, 3.7987922178020392, 3.7983915624195976, 3.7967120409455086, 3.7950276605285787, 3.793570524958131, 3.7924932393983237, 3.7917953877709594, 3.790747355173796, 3.7904745780331788, 3.7890431987694697, 3.788387523691514, 3.7878825508789293, 3.787881592116121, 3.782281747333668, 3.7811535273384416, 3.7776949348750013, 3.775931849402528, 3.7748490880688226, 3.773403352612598, 3.7673740086555445, 3.765421982052917, 3.7652893216478325, 3.7637907572385685, 3.7631844507911616, 3.761568512925348, 3.761568512925348, 3.759952985460944, 3.7598752007882186, 3.7591231104597522, 3.7561179536336935, 3.7552741607347215, 3.7538829996426974, 3.747359611227375, 3.7439600348998487, 3.7349725287648496, 3.73189202311063, 3.7308166811046735, 3.729671987645919, 3.7294156943538512, 3.728775284627958, 3.724062988413016, 3.7238369266504017, 3.7218789124212877, 3.72120986416305, 3.719409786710631, 3.7165538521627424, 3.7158259764434494, 3.7089486171339052, 3.7048814364880114, 3.7029185094609627, 3.7003433673094275, 3.699618962459593, 3.698353309878781, 3.697750681840472, 3.6972256808198316, 3.686956587680017, 3.686714317494224, 3.6849682452360852, 3.682737145158144, 3.6825641123161996, 3.682390944354166, 3.6759969183304575, 3.675959644265375, 3.6747756063780725, 3.674393514412238, 3.6708653654250227, 3.6703030280178828, 3.6692836756721596, 3.667447541214027, 3.667447541214027, 3.6669411893755433, 3.6666224095994555, 3.665151616530634, 3.664261422999685, 3.6637986124162074, 3.663253018112321, 3.6623999706269585, 3.6605722346344938, 3.6580948622141904, 3.6565327356731787, 3.65484242865999, 3.6534641813991, 3.650921977010119, 3.647882543868515, 3.6476201476638743, 3.6404958677685952, 3.6380590947672617, 3.6378579615559676, 3.6278592952664908, 3.62415477781738, 3.621151000638641, 3.6209607601754734, 3.6178207104735933, 3.6168465938246848, 3.6166255117245707, 3.615676603043861, 3.6156577025184378, 3.61239348054782, 3.610243643037911, 3.6082346356721122, 3.6065886978713353, 3.6058199085761364, 3.605818532678692, 3.6031154254941926, 3.6013575059352005, 3.598360076023422, 3.5976665579351437, 3.5959310953594894, 3.592006523367127, 3.5918388520622173, 3.5914100779448703, 3.5893490921051434, 3.587146860411652, 3.58551354780747, 3.5833274526053502, 3.5827308336036863, 3.5825183625986665, 3.5823030120883477, 3.5815397729768925, 3.5808011435853704, 3.579888855944302, 3.5766203307377973, 3.5743586730861043, 3.571392276191423, 3.5706725063060274, 3.5699769840968103, 3.5699388536384813, 3.5696820295643166, 3.569511181102179, 3.566631195676715, 3.5662747213384365, 3.5633149930317645, 3.562903658646419, 3.5625417005126088, 3.5601944148797253, 3.559887020828203, 3.5580005209725694, 3.5575965194568284, 3.5557758002961983, 3.555574122217285, 3.5546207989554954, 3.553328391772581, 3.552090197814463, 3.551724769151396, 3.547410575531953, 3.547410575531953, 3.547410575531953, 3.5473538244370952, 3.5461203096307297, 3.5453998468374706, 3.5392008440551, 3.5382232120824684, 3.5377241978496996, 3.5371544609194436, 3.5371086029233467, 3.536175708647767, 3.533708408463808, 3.533388938141182, 3.5266981213296895, 3.5249884884262905, 3.524953793452084, 3.5207241154926114, 3.5181192824951157, 3.514490405922484, 3.513654670832614, 3.5130527351233836, 3.5126514738323147, 3.5104740698400936, 3.5100081783364105, 3.5091231104597522, 3.508937831395352, 3.5063114747395185, 3.5036127600740543, 3.501769448726533, 3.499803529733168, 3.4987780454552313, 3.4987698040110278, 3.4937723691141946, 3.4934548680296293, 3.4925663375980713, 3.4899098452660513, 3.480546593008552, 3.48009111814914, 3.478808340838042, 3.4774397553122576, 3.4744205657614806, 3.474263876057954, 3.47415487701872, 3.4721966903626678, 3.4719130182684275, 3.471153692243344, 3.464428888804665, 3.4606990924446177, 3.4586009211555653, 3.456706934485565, 3.4556038160132134, 3.4525781540549603, 3.4521365848809014, 3.4493055948250655, 3.4490598708451707, 3.444241016586283, 3.443895657383066, 3.443569235741759, 3.4412050426729652, 3.439656373713982, 3.4366032449254655, 3.435460752147963, 3.4354166121901635, 3.4342922466746812, 3.433923502348209, 3.4336021438401074, 3.4335373070975774, 3.4329287715222687, 3.4316488018357476, 3.430574409943028, 3.429761736497063, 3.4297583028962886, 3.426541492210033, 3.4245907046379456, 3.4216022691866765, 3.421468518634086, 3.4148615444090464, 3.4133796415266175, 3.4119424097439697, 3.411791108156889, 3.407426580455378, 3.4062055073047532, 3.4047538843853347, 3.403843133182326, 3.403824976396743, 3.403438832742095, 3.3994269264893084, 3.3986488079248267, 3.3982943229218003, 3.3971812127465584, 3.393772748482759, 3.38949231169368, 3.38925775593173, 3.384077633619494, 3.383568240293699, 3.379257969567684, 3.3768783414297014, 3.3757700617420205, 3.3740735222095855, 3.3724227832767584, 3.3723110102922584, 3.3690221507704003, 3.3689887520310977, 3.3660853749858286, 3.3635482212327092, 3.3630245216434913, 3.357980195667377, 3.3564058311633236, 3.3559783510274928, 3.355864742294238, 3.3539423717172507, 3.3521321169604907, 3.347117214192062, 3.345206919022531, 3.3427775458598132, 3.3397561128539603, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.336583451882257, 3.336583451882257, 3.3348733915355853, 3.3316625099370465, 3.326475901080365, 3.323002049162362, 3.3213683211210667, 3.3212253477363602, 3.3207097658565266, 3.3191800454925295, 3.317841468468931, 3.3177358177364886, 3.3175413075140914, 3.314566399430134, 3.3091014830419225, 3.3074342160048813, 3.30670769891726, 3.3052678063595433, 3.302572422906542, 3.3000043034086124, 3.2980601556075784, 3.2952469348965887, 3.2949633051193543, 3.2935250343414464, 3.2920400838360493, 3.2919082414494722, 3.291598913772735, 3.287142013223335, 3.284578043715738, 3.284576657010512, 3.283705586609148, 3.2829900140218267, 3.282957993602375, 3.281699998486379, 3.2762703572963963, 3.2754900373639897, 3.274438621859733, 3.2738417758450353, 3.272534623342567, 3.2713993455499466, 3.268367868146374, 3.2681257561582497, 3.2650480279622873, 3.2630711121366596, 3.2627975286545627, 3.261937116862451, 3.258720294723259, 3.2576708002199233, 3.2538829996426974, 3.2538829996426974, 3.2538829996426974, 3.2518511145448348, 3.24931021068547, 3.2485099807284663, 3.2484561427317113, 3.247600940431324, 3.247600940431324, 3.247600940431324, 3.247600940431324, 3.247600940431324, 3.247058510897085, 3.2443273465513194, 3.2437902390149884, 3.243122197474161, 3.242532327369194, 3.2342164008530747, 3.232851228802909, 3.2313163947278167, 3.231233631165563, 3.231169515950617, 3.2300774433177235, 3.229418555305203, 3.2277764822437183, 3.224485824172842, 3.2181366664463513, 3.215430008700659, 3.2138016767725146, 3.213028063419412, 3.2123826592037488, 3.211691577407004, 3.209142847285123, 3.202328062555209, 3.197788729541031, 3.1975524787916587, 3.196825062675372, 3.1958013969338546, 3.1953308250295502, 3.1953106564774827, 3.1947190896214064, 3.193788839135776, 3.189356027742419, 3.187424708978892, 3.186791130226906, 3.1841924155791443, 3.1841011805221915, 3.1833502344823588, 3.1830229379154122, 3.180218557331721, 3.180041507854307, 3.177428121563592, 3.1769840237298586, 3.176477634524031, 3.1718546363690807, 3.16832932564756, 3.164481936089087, 3.155960784575859, 3.1545880434440186, 3.154399503548918, 3.151197094707099, 3.1491011171250505, 3.1485737992691343, 3.1450156918618526, 3.1431554444150747, 3.1429837061451207, 3.141934646459016, 3.1305687091883327, 3.1299626311846125, 3.1255086952840294, 3.1248878014864365, 3.1225388283031195, 3.122298085588591, 3.120151448364538, 3.1198984473294975, 3.1186976274434866, 3.116917362674728, 3.1117016608019337, 3.11143916797827, 3.1109715315870115, 3.1052726251760614, 3.101459382902342, 3.097135642106015, 3.095748560821543, 3.094930448367912, 3.0945521024662703, 3.093319851043336, 3.0914928155677956, 3.0911818695796547, 3.087614418733186, 3.085572513986991, 3.08498427095362, 3.0838589693201097, 3.0835084948792177, 3.082232279678722, 3.080921015560898, 3.0797281487638926, 3.079038910470409, 3.0758339259004672, 3.074920858405297, 3.074829523567363, 3.0747810836506124, 3.0714255586070083, 3.069851299548099, 3.0692552825394115, 3.0687665309166836, 3.068294515462989, 3.067514342915295, 3.067100788779973, 3.0670603445698337, 3.0667485658020874, 3.063026004046456, 3.0621244352766266, 3.061464178252013, 3.0595086427395257, 3.057872051816297, 3.0565157664345173, 3.0545136649232227, 3.0531800668467093, 3.05285463199396, 3.04651899246237, 3.045002283905662, 3.0449025141301447, 3.044571765338649, 3.0431651144194674, 3.042132825464557, 3.041673457371065, 3.040444038117414, 3.0403020996216576, 3.0392739314358668, 3.0389232317151316, 3.0383091338208805, 3.034561981229438, 3.034037336347814, 3.033893058266596, 3.033254254911831, 3.032135997254506, 3.0288597970125357, 3.0282403467208368, 3.023027585807462, 3.0198291788055878, 3.01806699404498, 3.0123641680866493, 3.011382091934431, 3.010601046687106, 3.010507083044987, 3.0061592372536667, 3.0052807338801357, 3.002892366128741, 3.0026747166567205, 3.00063328749088, 3.0006166830439085, 2.9980166582777152, 2.997465668697111, 2.9970175739393126, 2.996825520157748, 2.9966303845009508, 2.9963637934910112, 2.995436812959025, 2.995149571074338, 2.99346466559446, 2.992996329191986, 2.9915574723102143, 2.9915173317598787, 2.9904201551786627, 2.9887914780411657, 2.9862090348377945, 2.9852907383582905, 2.984329953917363, 2.9842191080399436, 2.983594457913341, 2.9831081602932015, 2.9825517248465285, 2.981489873201771, 2.981239926974052, 2.9802529706230207, 2.9790821151786693, 2.9782575709288044, 2.9766951441578766, 2.9754705495583256, 2.974651981774051, 2.974430347627506, 2.9735223211933315, 2.9732342380315067, 2.9729222097732366, 2.971980262613643, 2.971165893337201, 2.967972258769404, 2.96632963804466, 2.965597597280361, 2.964585502373318, 2.9633021259880246, 2.9605426637449126, 2.959604437259775, 2.9587502658160565, 2.958181042605414, 2.957844138311141, 2.956611363837554, 2.9557684819831738, 2.9543192365420654, 2.9542604109703587, 2.950171336860859, 2.9492989788923705, 2.9464239705926696, 2.9437502150595454, 2.942276951968485, 2.940221236143116, 2.9358437393642713, 2.93484046881041, 2.933606244465947, 2.9292644956181815, 2.927837387091414, 2.927255782041217, 2.9267433404945753, 2.923496285978093, 2.9225270138111825, 2.917009774408792, 2.9158174344518115, 2.9151156583448836, 2.9110316372776315, 2.9104848116251, 2.90877595358365, 2.907719716643427, 2.9020132133945613, 2.9000276428811804, 2.8995368994695587, 2.8992357418996164, 2.8985808642652473, 2.897556348170099, 2.890460820690773, 2.889574621070571, 2.889239878714739, 2.8888194393271753, 2.8865039592007475, 2.885710639220932, 2.8856687515265556, 2.8841639179307013, 2.8836543342735275, 2.880689220798142, 2.8791366234244253, 2.8770706152315695, 2.8761909525597993, 2.8752207283641686, 2.871277208058845, 2.870403249243351, 2.869725872842892, 2.8684229019079, 2.867962518626905, 2.860095693779904, 2.8592542797943707, 2.8587114985296562, 2.8577307736088495, 2.8538425481812038, 2.8537491209516834, 2.851292641123276, 2.8499830321011594, 2.848094797674195, 2.8451429388278324, 2.844395757920564, 2.844215566828725, 2.842371112930547, 2.8414228019817735, 2.838899412676545, 2.8388236484625, 2.836601978050259, 2.8360807116803035, 2.834413373251349, 2.8322148827682065, 2.8283614518682043, 2.8272386193923045, 2.825696880767518, 2.825608842670195, 2.8253863127368275, 2.8252666628658276, 2.8225655018416846, 2.821254710110685, 2.8210513379019577, 2.818814035333933, 2.8169109191437327, 2.8155216803887506, 2.8151930332869863, 2.8139466896914027, 2.813827687265185, 2.8131183397493733, 2.8116074354735145, 2.8105790362973577, 2.8100486996669924, 2.8097103629447333, 2.8078443731284457, 2.8064986488900003, 2.806403900475109, 2.804036512253919, 2.801813641926952, 2.8011597864573483, 2.801006740198342, 2.800305784640983, 2.79945167626507, 2.795909467068479, 2.7942316565100627, 2.7937919468456625, 2.7936819437263063, 2.7919082414494722, 2.7912040461371648, 2.791055401605772, 2.7909623271161426, 2.788915090280857, 2.779685167438475, 2.7792080209851644, 2.7743680718125323, 2.7738243735537904, 2.7708037702166215, 2.7666930874598386, 2.765599758970186, 2.764596520239219, 2.760135563746883, 2.7591902586013104, 2.7591231104597522, 2.758400610829351, 2.7572406173312762, 2.756564022175375, 2.7565626973462223, 2.756413212795758, 2.754959725037132, 2.7546572208237174, 2.7538829996426974, 2.7538829996426974, 2.7538829996426974, 2.7538829996426974, 2.7538829996426974, 2.7538829996426974, 2.7538829996426974, 2.7538829996426974, 2.7538829996426974, 2.7534883480626537, 2.7523089152567874, 2.751608989409479, 2.7499481990267416, 2.747741739375934, 2.7473201003052523, 2.7434355079790587, 2.7422681224156906, 2.742018544694607, 2.741548989551745, 2.741017602665968, 2.740085438181291, 2.7375156692537694, 2.7341546244945114, 2.7335907503164023, 2.7330179837701163, 2.7326539993675856, 2.732445747490398, 2.7316329846749716, 2.7313950914146288, 2.7294504985453845, 2.7281505996423565, 2.7267844435353847, 2.725354804482844, 2.724016655572957, 2.7236787230483355, 2.723039069679491, 2.7164459095828803, 2.715489761733871, 2.71544887460102, 2.714892154653138, 2.7148513205817544, 2.7147106199365254, 2.7124025059301404, 2.710137143691102, 2.709051488304149, 2.708850971397558, 2.7070710863477405, 2.7038060680830225, 2.7032895247280706, 2.7029178147890516, 2.7015379057838977, 2.698401398218447, 2.6975578512047, 2.6947789653568446, 2.6936249322649397, 2.6911674916547774, 2.690651920235212, 2.6894098204669863, 2.6887009195098255, 2.688644025775464, 2.688611742944707, 2.687465842600279, 2.6851416453611936, 2.682234937837479, 2.6772567789424744, 2.6764045046597045, 2.676138025071818, 2.6751195816091338, 2.674900679694135, 2.6743202004509006, 2.6733064436170393, 2.670398051966249, 2.668906273024148, 2.667447541214027, 2.6671504650442133, 2.6648793074642434, 2.664199609204622, 2.6634921868244144, 2.663304179021171, 2.661885774595235, 2.6539678670040567, 2.653874478428992, 2.653316805578454, 2.6527116389247585, 2.6521099680758846, 2.649518622309301, 2.6478444670080306, 2.6454668906312957, 2.6438338802665906, 2.63883030080647, 2.637712539602197, 2.637477385789043, 2.635749419246308, 2.634890936112585, 2.6319520293117256, 2.6311921812370054, 2.6310334487168143, 2.6310227242797146, 2.629906374835574, 2.628754836205374, 2.625167303207165, 2.624824230906483, 2.6167190289604028, 2.6162232418653524, 2.608732285189654, 2.6026983991922705, 2.6007470883776733, 2.600602098579744, 2.596381863889337, 2.59614568966937, 2.595977998515805, 2.5923898609052616, 2.5916205070533027, 2.590224844972422, 2.589366862396055, 2.5880866617208023, 2.5837677311926983, 2.583482250125854, 2.582640456731178, 2.582610675310721, 2.5823647961308107, 2.5822264046422205, 2.5820994338618006, 2.578097422380135, 2.5776156934296424, 2.5768499215950396, 2.5764288416420893, 2.575799831158036, 2.573948833814846, 2.572383849436431, 2.5704176864613064, 2.5645677570222416, 2.561817518141401, 2.55848895380408, 2.555802250832658, 2.55515055085213, 2.551812456529998, 2.551416404369653, 2.550754552527922, 2.5482629523172817, 2.5443980

In [7]:
print(itemgetter(*sort_new)(prediction_user_4_fold_1))

(5.719023742583455, 5.411684566864092, 5.273543266278282, 5.21471607869225, 5.132335552348402, 5.103802202042152, 4.977452813936131, 4.944970072759129, 4.883004717056317, 4.866108797035027, 4.861462301991333, 4.85559627389256, 4.838079720149866, 4.835140077579352, 4.815193033286986, 4.790826816560027, 4.772003337835814, 4.745408123360261, 4.725801702422762, 4.70282951036911, 4.696842996267967, 4.696342857271082, 4.6787480845711436, 4.659379781625404, 4.658434937778645, 4.6223067023055195, 4.603920120975594, 4.599689311942579, 4.59890783253499, 4.597882400586642, 4.591633441563337, 4.583237677023467, 4.574226928941219, 4.572459425711541, 4.566943830371889, 4.5444511632677935, 4.5295682589587285, 4.520784778730045, 4.5187123561479465, 4.518069953296329, 4.501029114117525, 4.499917301079998, 4.493931447884263, 4.49340029786065, 4.490346722836932, 4.488984294707959, 4.488765481925839, 4.487582468585395, 4.467946678279443, 4.457140821443113, 4.4570158764533545, 4.449693628544859, 4.431817377065781, 4.428848272506799, 4.427233665465401, 4.421530399370945, 4.421312589424365, 4.419815365782555, 4.4164977906776475, 4.416292963685212, 4.410989060528821, 4.398636018444293, 4.38076220127193, 4.367460847555337, 4.366396565423121, 4.361568512925348, 4.353611607619695, 4.339083078792268, 4.339083078792268, 4.339083078792268, 4.339083078792268, 4.339083078792268, 4.33757623247855, 4.334944980239607, 4.331163953699349, 4.328274738572635, 4.324449247036821, 4.32193788672475, 4.321738464714917, 4.320225764130328, 4.315473081648159, 4.310090945465983, 4.307434216004881, 4.294832028445219, 4.2947240266473665, 4.290008931004416, 4.281256259196493, 4.275649995301228, 4.273712874549959, 4.273508805561918, 4.273068934980786, 4.2666317704517835, 4.266074158868611, 4.264579448877906, 4.257243931868371, 4.235605236717855, 4.2351055756040985, 4.22742253048905, 4.22168342911256, 4.217961379885038, 4.21481363712266, 4.211792644523609, 4.211210451700008, 4.20812865291658, 4.193961614104181, 4.18747930825859, 4.182340115057445, 4.177869719812231, 4.176415666542552, 4.168096382488743, 4.1677775571126245, 4.163414930905885, 4.16086942343503, 4.160399488963508, 4.157178197189912, 4.155953259881575, 4.155740124903999, 4.150776926418557, 4.14561972514411, 4.143534281697264, 4.132638561138626, 4.132576878770743, 4.131793771451236, 4.1107748422660535, 4.107991500071364, 4.101572546411382, 4.101128519860383, 4.1000407452412375, 4.099661823643011, 4.0985275918671835, 4.098140812187357, 4.094768201345678, 4.08725109598721, 4.084545916512057, 4.0816747494220476, 4.071820154969777, 4.070421284354029, 4.0673013745611515, 4.066836693917783, 4.066544713334677, 4.064149648171151, 4.055580728051427, 4.048464442070771, 4.0479462936294155, 4.045204955135248, 4.037342130232604, 4.036830249788061, 4.03319364226134, 4.032686068509291, 4.0270829216386685, 4.026270120695139, 4.024921011763943, 4.023141055386433, 4.022747584866865, 4.021480238321548, 4.013691445843194, 4.013375082156746, 4.012994575715253, 4.007000771865345, 4.005746768570241, 4.00078087454736, 4.000405879902646, 4.000275283356235, 3.9995263868029975, 3.9966471351550603, 3.9958011267836056, 3.9932001387898097, 3.984277545814703, 3.980925036291824, 3.975069889364047, 3.974686294488171, 3.9726385943919182, 3.9725691335946727, 3.972334013309839, 3.971557348153288, 3.970352935592609, 3.967665663450262, 3.9643123479353517, 3.9627266512091137, 3.9615908573792655, 3.9593424126097165, 3.9513969505164215, 3.951212694262985, 3.950322592989491, 3.950172175045265, 3.947286548492931, 3.9385732781503178, 3.938191264272813, 3.936541929198351, 3.933788869374825, 3.931445634211394, 3.930261019020359, 3.9300088474894963, 3.928536531223316, 3.928151390813076, 3.923600941840118, 3.923524220083355, 3.9216338495218235, 3.9206603622586513, 3.918862836199931, 3.9176136815843443, 3.915368098855859, 3.914957240658885, 3.9112466286898164, 3.910989060528821, 3.9000599171130506, 3.899294510513481, 3.897880681745347, 3.8976531163175347, 3.895138173166312, 3.8879892234237525, 3.8869732626892444, 3.8836136428382706, 3.8765420645707365, 3.8762669464068864, 3.868050347455206, 3.8674308484683944, 3.864905400076575, 3.8636363241024383, 3.8628046487967755, 3.857344807625074, 3.857129200855867, 3.8470788472183037, 3.844324755918976, 3.8428283748176653, 3.8410296951222085, 3.840114637103076, 3.836583451882257, 3.8342010572387983, 3.828128262920264, 3.826882881473203, 3.8248445182679345, 3.822915709205076, 3.822738581766575, 3.8224697634046025, 3.818853366706487, 3.818287908531554, 3.8175750985106367, 3.8120546484117144, 3.810552516596056, 3.8103311104068665, 3.8098668725570968, 3.809058209335348, 3.803956873752439, 3.801802035122493, 3.7987922178020392, 3.7983915624195976, 3.7967120409455086, 3.7950276605285787, 3.793570524958131, 3.7924932393983237, 3.7917953877709594, 3.790747355173796, 3.7904745780331788, 3.7890431987694697, 3.788387523691514, 3.7878825508789293, 3.787881592116121, 3.782281747333668, 3.7811535273384416, 3.7776949348750013, 3.775931849402528, 3.7748490880688226, 3.773403352612598, 3.7673740086555445, 3.765421982052917, 3.7652893216478325, 3.7637907572385685, 3.7631844507911616, 3.761568512925348, 3.761568512925348, 3.759952985460944, 3.7598752007882186, 3.7591231104597522, 3.7561179536336935, 3.7552741607347215, 3.7538829996426974, 3.747359611227375, 3.7439600348998487, 3.7349725287648496, 3.73189202311063, 3.7308166811046735, 3.729671987645919, 3.7294156943538512, 3.728775284627958, 3.724062988413016, 3.7238369266504017, 3.7218789124212877, 3.72120986416305, 3.719409786710631, 3.7165538521627424, 3.7158259764434494, 3.7089486171339052, 3.7048814364880114, 3.7029185094609627, 3.7003433673094275, 3.699618962459593, 3.698353309878781, 3.697750681840472, 3.6972256808198316, 3.686956587680017, 3.686714317494224, 3.6849682452360852, 3.682737145158144, 3.6825641123161996, 3.682390944354166, 3.6759969183304575, 3.675959644265375, 3.6747756063780725, 3.674393514412238, 3.6708653654250227, 3.6703030280178828, 3.6692836756721596, 3.667447541214027, 3.667447541214027, 3.6669411893755433, 3.6666224095994555, 3.665151616530634, 3.664261422999685, 3.6637986124162074, 3.663253018112321, 3.6623999706269585, 3.6605722346344938, 3.6580948622141904, 3.6565327356731787, 3.65484242865999, 3.6534641813991, 3.650921977010119, 3.647882543868515, 3.6476201476638743, 3.6404958677685952, 3.6380590947672617, 3.6378579615559676, 3.6278592952664908, 3.62415477781738, 3.621151000638641, 3.6209607601754734, 3.6178207104735933, 3.6168465938246848, 3.6166255117245707, 3.615676603043861, 3.6156577025184378, 3.61239348054782, 3.610243643037911, 3.6082346356721122, 3.6065886978713353, 3.6058199085761364, 3.605818532678692, 3.6031154254941926, 3.6013575059352005, 3.598360076023422, 3.5976665579351437, 3.5959310953594894, 3.592006523367127, 3.5918388520622173, 3.5914100779448703, 3.5893490921051434, 3.587146860411652, 3.58551354780747, 3.5833274526053502, 3.5827308336036863, 3.5825183625986665, 3.5823030120883477, 3.5815397729768925, 3.5808011435853704, 3.579888855944302, 3.5766203307377973, 3.5743586730861043, 3.571392276191423, 3.5706725063060274, 3.5699769840968103, 3.5699388536384813, 3.5696820295643166, 3.569511181102179, 3.566631195676715, 3.5662747213384365, 3.5633149930317645, 3.562903658646419, 3.5625417005126088, 3.5601944148797253, 3.559887020828203, 3.5580005209725694, 3.5575965194568284, 3.5557758002961983, 3.555574122217285, 3.5546207989554954, 3.553328391772581, 3.552090197814463, 3.551724769151396, 3.547410575531953, 3.547410575531953, 3.547410575531953, 3.5473538244370952, 3.5461203096307297, 3.5453998468374706, 3.5392008440551, 3.5382232120824684, 3.5377241978496996, 3.5371544609194436, 3.5371086029233467, 3.536175708647767, 3.533708408463808, 3.533388938141182, 3.5266981213296895, 3.5249884884262905, 3.524953793452084, 3.5207241154926114, 3.5181192824951157, 3.514490405922484, 3.513654670832614, 3.5130527351233836, 3.5126514738323147, 3.5104740698400936, 3.5100081783364105, 3.5091231104597522, 3.508937831395352, 3.5063114747395185, 3.5036127600740543, 3.501769448726533, 3.499803529733168, 3.4987780454552313, 3.4987698040110278, 3.4937723691141946, 3.4934548680296293, 3.4925663375980713, 3.4899098452660513, 3.480546593008552, 3.48009111814914, 3.478808340838042, 3.4774397553122576, 3.4744205657614806, 3.474263876057954, 3.47415487701872, 3.4721966903626678, 3.4719130182684275, 3.471153692243344, 3.464428888804665, 3.4606990924446177, 3.4586009211555653, 3.456706934485565, 3.4556038160132134, 3.4525781540549603, 3.4521365848809014, 3.4493055948250655, 3.4490598708451707, 3.444241016586283, 3.443895657383066, 3.443569235741759, 3.4412050426729652, 3.439656373713982, 3.4366032449254655, 3.435460752147963, 3.4354166121901635, 3.4342922466746812, 3.433923502348209, 3.4336021438401074, 3.4335373070975774, 3.4329287715222687, 3.4316488018357476, 3.430574409943028, 3.429761736497063, 3.4297583028962886, 3.426541492210033, 3.4245907046379456, 3.4216022691866765, 3.421468518634086, 3.4148615444090464, 3.4133796415266175, 3.4119424097439697, 3.411791108156889, 3.407426580455378, 3.4062055073047532, 3.4047538843853347, 3.403843133182326, 3.403824976396743, 3.403438832742095, 3.3994269264893084, 3.3986488079248267, 3.3982943229218003, 3.3971812127465584, 3.393772748482759, 3.38949231169368, 3.38925775593173, 3.384077633619494, 3.383568240293699, 3.379257969567684, 3.3768783414297014, 3.3757700617420205, 3.3740735222095855, 3.3724227832767584, 3.3723110102922584, 3.3690221507704003, 3.3689887520310977, 3.3660853749858286, 3.3635482212327092, 3.3630245216434913, 3.357980195667377, 3.3564058311633236, 3.3559783510274928, 3.355864742294238, 3.3539423717172507, 3.3521321169604907, 3.347117214192062, 3.345206919022531, 3.3427775458598132, 3.3397561128539603, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.3390830787922683, 3.336583451882257, 3.336583451882257, 3.3348733915355853, 3.3316625099370465, 3.326475901080365, 3.323002049162362, 3.3213683211210667, 3.3212253477363602, 3.3207097658565266, 3.3191800454925295, 3.317841468468931, 3.3177358177364886, 3.3175413075140914, 3.314566399430134, 3.3091014830419225, 3.3074342160048813, 3.30670769891726, 3.3052678063595433, 3.302572422906542, 3.3000043034086124, 3.2980601556075784, 3.2952469348965887, 3.2949633051193543, 3.2935250343414464, 3.2920400838360493, 3.2919082414494722, 3.291598913772735, 3.287142013223335, 3.284578043715738, 3.284576657010512, 3.283705586609148, 3.2829900140218267, 3.282957993602375, 3.281699998486379, 3.2762703572963963, 3.2754900373639897, 3.274438621859733, 3.2738417758450353, 3.272534623342567, 3.2713993455499466, 3.268367868146374, 3.2681257561582497, 3.2650480279622873, 3.2630711121366596, 3.2627975286545627, 3.261937116862451, 3.258720294723259, 3.2576708002199233, 3.2538829996426974, 3.2538829996426974, 3.2538829996426974, 3.2518511145448348, 3.24931021068547, 3.2485099807284663, 3.2484561427317113, 3.247600940431324, 3.247600940431324, 3.247600940431324, 3.247600940431324, 3.247600940431324, 3.247058510897085, 3.2443273465513194, 3.2437902390149884, 3.243122197474161, 3.242532327369194, 3.2342164008530747, 3.232851228802909, 3.2313163947278167, 3.231233631165563, 3.231169515950617, 3.2300774433177235, 3.229418555305203, 3.2277764822437183, 3.224485824172842, 3.2181366664463513, 3.215430008700659, 3.2138016767725146, 3.213028063419412, 3.2123826592037488, 3.211691577407004, 3.209142847285123, 3.202328062555209, 3.197788729541031, 3.1975524787916587, 3.196825062675372, 3.1958013969338546, 3.1953308250295502, 3.1953106564774827, 3.1947190896214064, 3.193788839135776, 3.189356027742419, 3.187424708978892, 3.186791130226906, 3.1841924155791443, 3.1841011805221915, 3.1833502344823588, 3.1830229379154122, 3.180218557331721, 3.180041507854307, 3.177428121563592, 3.1769840237298586, 3.176477634524031, 3.1718546363690807, 3.16832932564756, 3.164481936089087, 3.155960784575859, 3.1545880434440186, 3.154399503548918, 3.151197094707099, 3.1491011171250505, 3.1485737992691343, 3.1450156918618526, 3.1431554444150747, 3.1429837061451207, 3.141934646459016, 3.1305687091883327, 3.1299626311846125, 3.1255086952840294, 3.1248878014864365, 3.1225388283031195, 3.122298085588591, 3.120151448364538, 3.1198984473294975, 3.1186976274434866, 3.116917362674728, 3.1117016608019337, 3.11143916797827, 3.1109715315870115, 3.1052726251760614, 3.101459382902342, 3.097135642106015, 3.095748560821543, 3.094930448367912, 3.0945521024662703, 3.093319851043336, 3.0914928155677956, 3.0911818695796547, 3.087614418733186, 3.085572513986991, 3.08498427095362, 3.0838589693201097, 3.0835084948792177, 3.082232279678722, 3.080921015560898, 3.0797281487638926, 3.079038910470409, 3.0758339259004672, 3.074920858405297, 3.074829523567363, 3.0747810836506124, 3.0714255586070083, 3.069851299548099, 3.0692552825394115, 3.0687665309166836, 3.068294515462989, 3.067514342915295, 3.067100788779973, 3.0670603445698337, 3.0667485658020874, 3.063026004046456, 3.0621244352766266, 3.061464178252013, 3.0595086427395257, 3.057872051816297, 3.0565157664345173, 3.0545136649232227, 3.0531800668467093, 3.05285463199396, 3.04651899246237, 3.045002283905662, 3.0449025141301447, 3.044571765338649, 3.0431651144194674, 3.042132825464557, 3.041673457371065, 3.040444038117414, 3.0403020996216576, 3.0392739314358668, 3.0389232317151316, 3.0383091338208805, 3.034561981229438, 3.034037336347814, 3.033893058266596, 3.033254254911831, 3.032135997254506, 3.0288597970125357, 3.0282403467208368, 3.023027585807462, 3.0198291788055878, 3.01806699404498, 3.0123641680866493, 3.011382091934431, 3.010601046687106, 3.010507083044987, 3.0061592372536667, 3.0052807338801357, 3.002892366128741, 3.0026747166567205, 3.00063328749088, 3.0006166830439085, 2.9980166582777152, 2.997465668697111, 2.9970175739393126, 2.996825520157748, 2.9966303845009508, 2.9963637934910112, 2.995436812959025, 2.995149571074338, 2.99346466559446, 2.992996329191986, 2.9915574723102143, 2.9915173317598787, 2.9904201551786627, 2.9887914780411657, 2.9862090348377945, 2.9852907383582905, 2.984329953917363, 2.9842191080399436, 2.983594457913341, 2.9831081602932015, 2.9825517248465285, 2.981489873201771, 2.981239926974052, 2.9802529706230207, 2.9790821151786693, 2.9782575709288044, 2.9766951441578766, 2.9754705495583256, 2.974651981774051, 2.974430347627506, 2.9735223211933315, 2.9732342380315067, 2.9729222097732366, 2.971980262613643, 2.971165893337201, 2.967972258769404, 2.96632963804466, 2.965597597280361, 2.964585502373318, 2.9633021259880246, 2.9605426637449126, 2.959604437259775, 2.9587502658160565, 2.958181042605414, 2.957844138311141, 2.956611363837554, 2.9557684819831738, 2.9543192365420654, 2.9542604109703587, 2.950171336860859, 2.9492989788923705, 2.9464239705926696, 2.9437502150595454, 2.942276951968485, 2.940221236143116, 2.9358437393642713, 2.93484046881041, 2.933606244465947, 2.9292644956181815, 2.927837387091414, 2.927255782041217, 2.9267433404945753, 2.923496285978093, 2.9225270138111825, 2.917009774408792, 2.9158174344518115, 2.9151156583448836, 2.9110316372776315, 2.9104848116251, 2.90877595358365, 2.907719716643427, 2.9020132133945613, 2.9000276428811804, 2.8995368994695587, 2.8992357418996164, 2.8985808642652473, 2.897556348170099, 2.890460820690773, 2.889574621070571, 2.889239878714739, 2.8888194393271753, 2.8865039592007475, 2.885710639220932, 2.8856687515265556, 2.8841639179307013, 2.8836543342735275, 2.880689220798142, 2.8791366234244253, 2.8770706152315695, 2.8761909525597993, 2.8752207283641686, 2.871277208058845, 2.870403249243351, 2.869725872842892, 2.8684229019079, 2.867962518626905, 2.860095693779904, 2.8592542797943707, 2.8587114985296562, 2.8577307736088495, 2.8538425481812038, 2.8537491209516834, 2.851292641123276, 2.8499830321011594, 2.848094797674195, 2.8451429388278324, 2.844395757920564, 2.844215566828725, 2.842371112930547, 2.8414228019817735, 2.838899412676545, 2.8388236484625, 2.836601978050259, 2.8360807116803035, 2.834413373251349, 2.8322148827682065, 2.8283614518682043, 2.8272386193923045, 2.825696880767518, 2.825608842670195, 2.8253863127368275, 2.8252666628658276, 2.8225655018416846, 2.821254710110685, 2.8210513379019577, 2.818814035333933, 2.8169109191437327, 2.8155216803887506, 2.8151930332869863, 2.8139466896914027, 2.813827687265185, 2.8131183397493733, 2.8116074354735145, 2.8105790362973577, 2.8100486996669924, 2.8097103629447333, 2.8078443731284457, 2.8064986488900003, 2.806403900475109, 2.804036512253919, 2.801813641926952, 2.8011597864573483, 2.801006740198342, 2.800305784640983, 2.79945167626507, 2.795909467068479, 2.7942316565100627, 2.7937919468456625, 2.7936819437263063, 2.7919082414494722, 2.7912040461371648, 2.791055401605772, 2.7909623271161426, 2.788915090280857, 2.779685167438475, 2.7792080209851644, 2.7743680718125323, 2.7738243735537904, 2.7708037702166215, 2.7666930874598386, 2.765599758970186, 2.764596520239219, 2.760135563746883, 2.7591902586013104, 2.7591231104597522, 2.758400610829351, 2.7572406173312762, 2.756564022175375, 2.7565626973462223, 2.756413212795758, 2.754959725037132, 2.7546572208237174, 2.7538829996426974, 2.7538829996426974, 2.7538829996426974, 2.7538829996426974, 2.7538829996426974, 2.7538829996426974, 2.7538829996426974, 2.7538829996426974, 2.7538829996426974, 2.7534883480626537, 2.7523089152567874, 2.751608989409479, 2.7499481990267416, 2.747741739375934, 2.7473201003052523, 2.7434355079790587, 2.7422681224156906, 2.742018544694607, 2.741548989551745, 2.741017602665968, 2.740085438181291, 2.7375156692537694, 2.7341546244945114, 2.7335907503164023, 2.7330179837701163, 2.7326539993675856, 2.732445747490398, 2.7316329846749716, 2.7313950914146288, 2.7294504985453845, 2.7281505996423565, 2.7267844435353847, 2.725354804482844, 2.724016655572957, 2.7236787230483355, 2.723039069679491, 2.7164459095828803, 2.715489761733871, 2.71544887460102, 2.714892154653138, 2.7148513205817544, 2.7147106199365254, 2.7124025059301404, 2.710137143691102, 2.709051488304149, 2.708850971397558, 2.7070710863477405, 2.7038060680830225, 2.7032895247280706, 2.7029178147890516, 2.7015379057838977, 2.698401398218447, 2.6975578512047, 2.6947789653568446, 2.6936249322649397, 2.6911674916547774, 2.690651920235212, 2.6894098204669863, 2.6887009195098255, 2.688644025775464, 2.688611742944707, 2.687465842600279, 2.6851416453611936, 2.682234937837479, 2.6772567789424744, 2.6764045046597045, 2.676138025071818, 2.6751195816091338, 2.674900679694135, 2.6743202004509006, 2.6733064436170393, 2.670398051966249, 2.668906273024148, 2.667447541214027, 2.6671504650442133, 2.6648793074642434, 2.664199609204622, 2.6634921868244144, 2.663304179021171, 2.661885774595235, 2.6539678670040567, 2.653874478428992, 2.653316805578454, 2.6527116389247585, 2.6521099680758846, 2.649518622309301, 2.6478444670080306, 2.6454668906312957, 2.6438338802665906, 2.63883030080647, 2.637712539602197, 2.637477385789043, 2.635749419246308, 2.634890936112585, 2.6319520293117256, 2.6311921812370054, 2.6310334487168143, 2.6310227242797146, 2.629906374835574, 2.628754836205374, 2.625167303207165, 2.624824230906483, 2.6167190289604028, 2.6162232418653524, 2.608732285189654, 2.6026983991922705, 2.6007470883776733, 2.600602098579744, 2.596381863889337, 2.59614568966937, 2.595977998515805, 2.5923898609052616, 2.5916205070533027, 2.590224844972422, 2.589366862396055, 2.5880866617208023, 2.5837677311926983, 2.583482250125854, 2.582640456731178, 2.582610675310721, 2.5823647961308107, 2.5822264046422205, 2.5820994338618006, 2.578097422380135, 2.5776156934296424, 2.5768499215950396, 2.5764288416420893, 2.575799831158036, 2.573948833814846, 2.572383849436431, 2.5704176864613064, 2.5645677570222416, 2.561817518141401, 2.55848895380408, 2.555802250832658, 2.55515055085213, 2.551812456529998, 2.551416404369653, 2.550754552527922, 2.5482629523172817, 2.5443980

In [21]:
print(evaluation.getItemTest(4,indexTrain=0))

[0, 1, 16, 23, 39, 41, 61, 68, 78, 79, 88, 89, 93, 97, 99, 101, 108, 109, 138, 142, 143, 152, 153, 166, 172, 175, 184, 208, 210, 213, 218, 221, 224, 226, 229, 230, 233, 240, 242, 258, 266, 362, 363, 368, 369, 371, 375, 376, 378, 381, 383, 384, 387, 388, 390, 392, 393, 396, 399, 401, 402, 406, 409, 410, 412, 416, 417, 420, 421, 422, 423, 425, 427, 428, 432, 434, 435, 438, 440, 443, 444, 452, 453, 456]

In [27]:
print(len(evaluation.getItemTest(4,indexTrain=0)))
print(len(evaluation.getItem(4,interacted=False,indexTrain=0)))

84
1591

In [4]:
import numpy as np

u = 4
indexTrain = 0

gt = np.array([1 if (evaluation.get_top_n_specific_user(u,indexTrain=indexTrain)[:i+1][-1] in evaluation.getItemTest(u,indexTrain)) and len(evaluation.getItemTest(4,0)) > i else 0 for i in range(30)])

In [23]:
print(gt)

[0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]

In [8]:
evaluaton.NDCG(4,0)

DCG =  0.8268713198217252 IDCG =  9.161581041840885

np.float64(0.09025421660796416)

In [ ]:
evaluaton.result_evaluation

np.float64(0.00762817298253006)

In [ ]:
import numpy as np
test = np.log2(np.arange(2,30+2)).real
print(test)
print(len(test))
print(np.arange(2,30+2))

[1.         1.5849625  2.         2.32192809 2.5849625  2.80735492
 3.         3.169925   3.32192809 3.45943162 3.5849625  3.70043972
 3.80735492 3.9068906  4.         4.08746284 4.169925   4.24792751
 4.32192809 4.39231742 4.45943162 4.52356196 4.5849625  4.64385619
 4.70043972 4.7548875  4.80735492 4.857981   4.9068906  4.95419631]
30
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31]