In [7]:
# from openpyxl import Workbook

# import the python pandas package
import pandas as pd
 
# create  data_frame1 by creating a dictionary
# in which values are stored as list
data_frame1 = pd.DataFrame({'Fruits': ['Appple', 'Banana', 'Mango',
                                       'Dragon Fruit', 'Musk melon', 'grapes'],
                            'Sales in kg': [21, 30, 15, 10, 50, 40]})
 
# create  data_frame2 by creating a dictionary 
# in which values are stored as list
data_frame2 = pd.DataFrame({'Vegetables': ['tomato', 'Onion', 'ladies finger',
                                           'beans', 'bedroot', 'carrot'],
                            'Sales in kg': [200, 310, 115, 110, 55, 45]})
 
# create  data_frame3 by creating a dictionary 
# in which values are stored as list
data_frame3 = pd.DataFrame({'Baked Items': ['Cakes', 'biscuits', 'muffins',
                                            'Rusk', 'puffs', 'cupcakes'],
                            'Sales in kg': [120, 130, 159, 310, 150, 140]})
 
print(data_frame1)
print(data_frame2)
print(data_frame3)
 
# create a excel writer object
with pd.ExcelWriter("filename.xlsx") as writer:
   
    # use to_excel function and specify the sheet_name and index 
    # to store the dataframe in specified sheet
    data_frame1.to_excel(writer, sheet_name="Fruits", index=False)
    data_frame2.to_excel(writer, sheet_name="Vegetables", index=False)
    data_frame3.to_excel(writer, sheet_name="Baked Items", index=False)

         Fruits  Sales in kg
0        Appple           21
1        Banana           30
2         Mango           15
3  Dragon Fruit           10
4    Musk melon           50
5        grapes           40
      Vegetables  Sales in kg
0         tomato          200
1          Onion          310
2  ladies finger          115
3          beans          110
4        bedroot           55
5         carrot           45
  Baked Items  Sales in kg
0       Cakes          120
1    biscuits          130
2     muffins          159
3        Rusk          310
4       puffs          150
5    cupcakes          140

In [8]:
import pandas as pd
    
old_data = pd.read_excel("filename.xlsx",sheet_name="Vegetables")

In [9]:
old_data

      Vegetables  Sales in kg
0         tomato          200
1          Onion          310
2  ladies finger          115
3          beans          110
4        bedroot           55
5         carrot           45

In [10]:
basket = {"ring" : []}
balls = ["Volley","Sattle Cock","Foot Ball","Basket Ball"]

for i in balls :
    basket["ring"] += [i]

In [11]:
import pandas as pd

metadata = {
    "alpa_1": [],
    "alpa_2": [],
    "k": [],
}

alpha_1 = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
alpha_2 = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]

k = [5,10,15,18,20,25,30,40,50,100,200]

for a in alpha_1 :
    for b in alpha_2 :
        for c in k :
            metadata["alpa_1"] += [a]
            metadata["alpa_2"] += [b]
            metadata["k"] += [c]


metadata = pd.DataFrame(metadata)

with pd.ExcelWriter("evaluation.xlsx") as writer :
    metadata.to_excel(writer,sheet_name="user-based")

In [12]:
from MatrixRating import MatrixRating

df = MatrixRating("data/ml-100k")

KeyboardInterrupt:

In [ ]:
df.show_dataset()

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
import pandas as pd
import numpy as np
import openpyxl

print(pd.__version__)
print(np.__version__)
print(openpyxl.__version__)

p = None
print(p is not None)

2.2.3
2.2.5
3.1.5
False

In [1]:
import Evaluation as E 
import DistanceBased.similarities as S 

ti = S.TI("data/ml-100k",opsional="user-based",alpha_1=0.1,alpha_2=0.5,k=5)

evaluaton = E.NDCG("data/ml-100k",ti.get_top_n(),toyData=False)

True
Train index = 0
Train index = 1
Train index = 2
Train index = 3
Train index = 4
Train index = 0
Train index = 1
Train index = 2
Train index = 3
Train index = 4
DCG =  0.23540891336663824 IDCG =  9.161581041840885
DCG =  0.2890648263178879 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.25 IDCG =  9.161581041840885
DCG =  0.22424382421757544 IDCG =  9.161581041840885
DCG =  0.6343633289973145 IDCG =  9.161581041840885
DCG =  0.6309297535714575 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.227670248696953 IDCG =  9.161581041840885
DCG =  0.2037950470905062 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.8886106766871936 IDCG =  9.161581041840885
DCG =  0.23981246656813146 IDCG =  9.161581041840885
DCG =  0.4836282735067685 IDCG =  9.161581041840885
DCG =  0.7210647294575038 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.31546487678572877 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.8417836205720385 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.2890648263178879 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.27023815442731974 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.23981246656813146 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.2890648263178879 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.23540891336663824 IDCG =  9.161581041840885
DCG =  0.21274605355336318 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.43322729974185903 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3010299956639812 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.22106472945750374 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.7720490342985709 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.43920396045714444 IDCG =  9.161581041840885
DCG =  0.5468430899454879 IDCG =  9.161581041840885
DCG =  0.27894294565112987 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.5 IDCG =  9.161581041840885
DCG =  0.2103099178571525 IDCG =  9.161581041840885
DCG =  0.5308031558224253 IDCG =  9.161581041840885
DCG =  0.64527201342591 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.38685280723454163 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.21810429198553155 IDCG =  9.161581041840885
DCG =  0.20184908658209985 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.21533827903669653 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3333333333333333 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.3154648767857289 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.5308031558224253 IDCG =  9.161581041840885
DCG =  0.21274605355336318 IDCG =  9.161581041840885
DCG =  0.7080145976765095 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.31546487678572877 IDCG =  9.161581041840885
DCG =  0.2037950470905062 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.21810429198553155 IDCG =  9.161581041840885
DCG =  0.22106472945750374 IDCG =  9.161581041840885
DCG =  0.5 IDCG =  9.161581041840885
DCG =  0.6795193352790528 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.359584708932084 IDCG =  9.161581041840885
DCG =  0.227670248696953 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.27023815442731974 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  2.1750113743189305 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.00774856995394 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.4369898777709386 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.23540891336663824 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.0 IDCG =  9.161581041840885
DCG =  0.7875818344226784 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.6309297535714575 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.27894294565112987 IDCG =  9.161581041840885
DCG =  0.455150745604828 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.5833333333333333 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.8877370701742734 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.25 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.23981246656813146 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.23981246656813146 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.21533827903669653 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3562071871080222 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.084072436632738 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.25 IDCG =  9.161581041840885
DCG =  0.23981246656813146 IDCG =  9.161581041840885
DCG =  0.2559580248098155 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.2181042919855316 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.9463946303571863 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3562071871080222 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.6549203822909685 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.0 IDCG =  9.161581041840885
DCG =  0.46307916206359123 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.27894294565112987 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3010299956639812 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3562071871080222 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3010299956639812 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.8870103429304476 IDCG =  9.161581041840885
DCG =  0.421185111497131 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.23137821315975915 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.6309297535714575 IDCG =  9.161581041840885
DCG =  0.20801459767650948 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.4364030084942003 IDCG =  9.161581041840885
DCG =  0.21533827903669653 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.227670248696953 IDCG =  9.161581041840885
DCG =  1.0 IDCG =  9.161581041840885
DCG =  0.27894294565112987 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.3724058347598547 IDCG =  9.161581041840885
DCG =  0.3333333333333333 IDCG =  9.161581041840885
DCG =  0.9060721466639499 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.20184908658209985 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.5 IDCG =  9.161581041840885
DCG =  0.8808325592788313 IDCG =  9.161581041840885
DCG =  0.6570909616618614 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.25 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.21533827903669653 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.23137821315975915 IDCG =  9.161581041840885
DCG =  1.2738365315982803 IDCG =  9.161581041840885
DCG =  0.20801459767650948 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.9559430711453059 IDCG =  9.161581041840885
DCG =  0.26264953503719357 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.8673499817827737 IDCG =  9.161581041840885
DCG =  0.31546487678572877 IDCG =  9.161581041840885
DCG =  0.3333333333333333 IDCG =  9.161581041840885
DCG =  1.198151135865074 IDCG =  9.161581041840885
DCG =  1.344591419041925 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  1.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.20801459767650948 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.671672063893751 IDCG =  9.161581041840885
DCG =  0.6822584218940849 IDCG =  9.161581041840885
DCG =  1.445266377393399 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.7254425743514558 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.21810429198553155 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.4322584218940849 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.6741698773972788 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.4844630086863575 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.2890648263178879 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.20584683246043448 IDCG =  9.161581041840885
DCG =  0.9567355787733668 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.22424382421757544 IDCG =  9.161581041840885
DCG =  0.750991981450045 IDCG =  9.161581041840885
DCG =  0.22424382421757544 IDCG =  9.161581041840885
DCG =  0.21533827903669653 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3562071871080222 IDCG =  9.161581041840885
DCG =  0.6309297535714575 IDCG =  9.161581041840885
DCG =  0.22424382421757544 IDCG =  9.161581041840885
DCG =  0.31546487678572877 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.24465054211822604 IDCG =  9.161581041840885
DCG =  0.31546487678572877 IDCG =  9.161581041840885
DCG =  0.2037950470905062 IDCG =  9.161581041840885
DCG =  0.26264953503719357 IDCG =  9.161581041840885
DCG =  0.26264953503719357 IDCG =  9.161581041840885
DCG =  0.2037950470905062 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.21533827903669653 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.5071691183034195 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3333333333333333 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.21533827903669653 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.22424382421757544 IDCG =  9.161581041840885
DCG =  0.4141049649476587 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.5308031558224253 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.865230300148121 IDCG =  9.161581041840885
DCG =  0.24465054211822604 IDCG =  9.161581041840885
DCG =  0.4844630086863575 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.227670248696953 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.9193281227426718 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.20584683246043448 IDCG =  9.161581041840885
DCG =  0.5031867698687054 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.6414571686987376 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.3562071871080222 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.21533827903669653 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.9397211514138837 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.7435037480938104 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.4478270642446409 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.7793846100520344 IDCG =  9.161581041840885
DCG =  0.227670248696953 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.27023815442731974 IDCG =  9.161581041840885
DCG =  0.5 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.2890648263178879 IDCG =  9.161581041840885
DCG =  0.27894294565112987 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.23137821315975915 IDCG =  9.161581041840885
DCG =  0.23981246656813146 IDCG =  9.161581041840885
DCG =  0.6309297535714575 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.26264953503719357 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.21533827903669653 IDCG =  9.161581041840885
DCG =  0.5 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885
DCG =  0.0 IDCG =  9.161581041840885

In [2]:
print(*evaluaton.get_top_n_specific_user(4,indexTrain=0))

829 1375 1141 1507 1275 804 1550 560 1561 1537 1408 1570 1357 1050 0 1148 927 594 1276 988 821 1544 1553 1558 1559 1066 1564 280 178 827 1097 386 225 761 1515 195 1101 71 1339 391 602 152 1432 1551 759 1252 851 1360 653 107 1030 686 1297 14 171 1306 775 278 701 102 151 10 552 913 876 1051 408 632 129 992 874 75 869 817 191 1266 56 1075 1547 200 640 915 222 871 830 1374 293 18 122 1109 79 814 615 1045 208 553 1255 97 1074 81 521 438 146 554 387 519 972 164 121 228 395 1077 549 20 1052 1038 1177 1296 643 745 758 1102 41 237 808 1524 174 317 155 428 382 1176 583 866 648 212 1027 398 161 877 257 165 423 1039 445 239 101 697 44 520 383 437 1304 977 1006 932 396 104 176 1407 1390 1445 112 160 1005 497 958 928 356 1283 140 245 261 918 1057 1229 333 88 1531 509 179 656 1370 7 1512 790 11 1099 993 488 862 389 3 555 514 68 262 649 354 357 235 25 1018 116 755 1414 925 148 420 658 1513 1058 273 371 1433 1308 1010 156 567 455 54 1502 351 1111 276 256 850 173 331 217 432 1019 981 1356 388 561 1210 26 67 579 21 1269 407 401 321 58 355 1342 654 290 792 113 1536 263 378 348 771 234 306 1508 198 435 367 439 182 879 119 130 511 501 105 254 1455 469 565 1285 994 516 847 1359 266 421 496 638 512 1046 947 1007 1391 598 172 580 404 747 377 190 230 1437 1427 569 843 618 144 684 440 1159 433 523 557 853 1128 243 1376 184 436 1044 1029 385 1501 810 609 1497 617 1024 62 929 796 111 763 1112 1554 1033 78 415 204 1170 833 1145 718 1028 1424 753 1393 210 150 338 80 917 1110 476 253 95 721 1377 780 1420 599 542 791 1124 249 430 272 232 419 1042 1500 1294 903 242 1095 1351 629 457 682 292 559 118 589 1337 167 525 406 857 136 458 1151 1298 1385 1575 1576 1578 65 6 394 474 613 103 1234 1076 291 1209 434 601 73 1011 1023 211 949 168 99 714 551 835 397 639 744 42 287 275 978 1278 319 872 400 518 1423 327 1295 1336 307 277 926 89 1449 1221 504 1015 831 878 626 1055 1528 897 279 399 1250 50 17 584 1523 218 133 1062 379 52 1446 489 337 1186 199 527 1314 1185 409 282 1293 670 663 157 403 1068 668 147 9 852 1119 154 818 1303 1486 1538 1540 1541 1543 1545 1546 1548 1549 1555 1557 203 644 985 1326 681 592 1353 1160 964 719 153 63 194 1236 823 61 1174 158 600 1443 422 27 1056 69 713 1206 563 930 255 522 1313 900 786 700 564 975 1264 166 220 524 1589 83 413 414 940 631 1081 192 288 743 1034 346 449 82 39 380 540 748 538 1277 442 23 495 1032 185 679 950 951 251 954 1106 676 431 24 844 418 120 1522 1566 127 138 1565 369 1082 361 250 976 335 441 1405 252 1067 1061 1026 1286 746 373 1493 1434 364 1411 188 650 297 46 417 370 922 1147 1043 1157 1125 581 1510 162 1103 669 4 1169 484 45 887 971 1189 1031 1190 924 304 139 515 305 299 429 473 135 888 1231 1270 1572 300 1009 1168 28 353 963 864 1355 1358 1368 935 260 652 322 776 1037 265 177 1241 881 1149 372 896 145 64 416 936 1519 1466 1364 1261 647 392 946 860 66 695 170 621 267 510 1239 451 989 1367 486 466 55 983 1582 1347 982 491 655 175 110 169 137 1392 708 281 1213 544 826 1220 1439 499 1535 84 1079 425 674 410 526 1398 1134 693 362 1280 189 216 1129 77 665 916 1452 556 193 855 87 1196 787 532 533 622 246 22 968 1431 269 712 375 628 541 774 1396 1191 816 762 607 1383 115 1132 349 562 1585 1468 1153 374 752 590 1104 1317 332 961 15 642 159 767 811 376 535 298 1022 974 892 1458 1069 633 678 1131 645 459 657 443 1289 13 1114 680 659 1419 1505 558 1389 461 546 919 717 637 838 29 970 475 689 1 270 1108 405 462 1288 912 402 660 1287 201 1425 452 47 1335 1463 181 623 94 797 426 1156 641 1461 702 1436 1481 624 233 1380 1238 427 1246 310 500 207 450 1422 302 754 1172 547 294 1382 106 1348 1323 268 943 1305 1117 393 358 572 1539 283 1290 341 901 16 764 772 1590 1418 1115 828 330 952 1175 286 769 123 180 1312 480 1450 620 736 832 1448 60 1409 1387 704 715 955 908 803 90 778 53 285 707 1192 96 920 795 465 662 1063 979 303 568 347 610 1116 1343 206 241 1105 868 215 923 1098 1091 446 1329 381 986 309 59 1583 1017 1399 873 236 424 350 1403 1016 1008 183 325 959 729 548 98 1100 875 1412 467 505 1386 953 902 513 611 705 85 240 1060 570 815 1338 19 942 756 825 807 1253 1395 672 593 323 271 1299 1302 517 1415 537 213 214 820 316 966 895 777 1094 673 732 1233 1237 1247 1248 1249 1257 1258 1260 1271 1274 858 845 812 1118 576 384 342 318 571 100 934 74 1527 973 37 1146 224 57 587 470 411 1309 478 566 482 35 481 882 460 86 141 197 550 149 1080 636 284 38 1181 226 806 1036 43 1203 444 1318 773 1126 1319 809 646 578 490 128 1113 1078 750 1334 329 603 49 390 40 492 1331 33 494 31 132 1084 1230 616 969 1047 530 1459 696 846 716 1430 1225 1025 51 320 880 143 782 528 867 1259 841 108 956 328 991 1001 1362 941 813 1232 125 464 296 664 997 483 1004 1506 948 163 34 1292 1496 1498 661 334 366 311 1136 1205 117 1243 931 1416 76 730 339 259 545 1464 630 1207 939 454 1127 870 8 126 1429 597 536 612 861 1053 911 1166 1021 231 1013 1321 690 709 30 606 683 1049 487 531 229 635 308 731 368 863 1404 131 1187 1193 675 1381 980 529 503 1499 448 1041 1267 1180 1183 819 468 907 1301 48 698 312 343 1426 733 890 1254 627 238 1164 906 1161 91 1325 1571 1573 1574 1577 962 360 849 340 1107 967 72 5 1453 1065 2 1330 345 574 1194 1223 1188 723 573 412 706 1373 477 586 801 1088 134 999 447 36 186 883 783 1130 534 692 1012 1214 1215 1242 1454 1456 1467 1472 1474 1475 1476 1477 1478 1479 1480 1482 1483 1484 1485 1487 1488 1489 1491 1492 1495 1035 848 1307 1378 314 326 1511 854 1245 336 1514 691 1457 1204 471 244 114 604 575 1460 741 585 614 885 699 1002 1372 1349 865 1014 1344 1462 1542 1556 720 264 840 1179 1090 582 1020 800 905 957 944 1384 1173 1120 1352 1003 781 1503 1504 768 258 788 124 1150 842 324 247 227 479 1086 248 789 990 784 1379 289 508 196 1165 933 1071 1530 1580 12 543 893 725 1171 1324 1509 1198 93 1133 728 142 1089 1235 836 1054 1163 70 909 694 1184 687 1332 751 591 1178 998 1291 605 1345 921 937 891 734 1361 1369 539 1152 1040 711 588 1240 209 1135 794 914 945 498 984 1563 1333 824 1350 651 1581 749 1139 1363 735 740 987 363 1310 1000 667 1518 453 295 301 219 313 1093 1354 822 726 1208 493 834 1447 1096 793 671 1322 766 837 502 1182 1211 1155 1315 1059 1388 608 739 904 1072 634 506 996 757 1122 205 1140 1346 315 1421 92 1273 1438 1123 910 472 727 1263 839 1222 1087 724 995 485 938 894 1440 898 965 889 1227 710 685 187 703 1216 802 221 1584 1073 688 886 1417 1137 1300 1199 625 1282 344 737 1167 1311 1435 1197 577 1048 1442 1397 779 960 1092 1162 1138 798 202 859 1142 1520 666 1327 109 1552 884 1121 1516 1268 595 1284 1226 1517 274 1320 742 456 1154 365 32 1279 463 899 677 1219 1195 1316 1328 1070 359 1212 799 1560 1202 1085 785 1568 1158 856 770 805 352 1262 1394 1402 223 1244 1534 596 1410 1224 1200 1569 1562 1526 1529 507 619 722 738 760 765 1064 1083 1143 1144 1201 1217 1218 1228 1251 1256 1265 1272 1281 1340 1341 1365 1366 1371 1400 1401 1406 1413 1428 1441 1444 1451 1465 1469 1470 1471 1473 1490 1494 1521 1525 1532 1533 1579 1586 1587 1588 1567

In [3]:
print(*evaluaton.getItemTest(4,0))

0 1 16 23 39 41 61 68 78 79 88 89 93 97 99 101 108 109 138 142 143 152 153 166 172 175 184 208 210 213 218 221 224 226 229 230 233 240 242 258 266 362 363 368 369 371 375 376 378 381 383 384 387 388 390 392 393 396 399 401 402 406 409 410 412 416 417 420 421 422 423 425 427 428 432 434 435 438 440 443 444 452 453 456

In [ ]:
import numpy as np

u = 1
indexTrain = 0

gt = np.array([1 if (evaluaton.get_top_n_specific_user(u,indexTrain=indexTrain)[:i+1][-1] in evaluaton.getItemTest(u,indexTrain)) and len(evaluaton.getItemTest(4,0)) > i else 0 for i in range(30)])

In [9]:
gt

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
evaluaton.NDCG(4,0)

DCG =  0.25 IDCG =  9.161581041840885

np.float64(0.02728786645648295)

In [5]:
evaluaton.result_evaluation

np.float64(0.00762817298253006)

In [ ]:
import numpy as np
test = np.log2(np.arange(2,30+2)).real
print(test)
print(len(test))
print(np.arange(2,30+2))

[1.         1.5849625  2.         2.32192809 2.5849625  2.80735492
 3.         3.169925   3.32192809 3.45943162 3.5849625  3.70043972
 3.80735492 3.9068906  4.         4.08746284 4.169925   4.24792751
 4.32192809 4.39231742 4.45943162 4.52356196 4.5849625  4.64385619
 4.70043972 4.7548875  4.80735492 4.857981   4.9068906  4.95419631]
30
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31]